name: ny_times_most_popular
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mockito: ^5.4.2
  dio: ^5.3.0
  provider: ^6.0.3
  retrofit: '>=4.0.0 <5.0.0'
  equatable: ^2.0.3
  lottie: ^2.5.0
  flutter_svg: ^2.0.5
  gap: ^2.0.0
  fancy_dio_inspector: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>2.3.0 <4.0.0'



flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
